[versions]
agp = "8.9.1"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
hiltversion = "2.57.1"
espressoCore = "3.6.1"
google-services = "4.4.2"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2025.02.00"
okHTTPClient = "4.12.0"
composeNavigation = "2.9.5"
hiltNavigation = "1.3.0"
vico = "2.0.2"
ksp = "2.0.0-1.0.22"
libLogfeast = "1.1.0"
firebaseStorage = "22.0.1"
accompanist = "0.25.1"
retrofit = "2.11.0"
firebase-bom = "34.9.0"

[libraries]
# core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
google-accompanist = {group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist"}
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

#Test cases
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#Retrofit
com-squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHTTPClient"}
squareup-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}

#vico charts
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

#Dipendency Injection: Helt depencencis
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltversion"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltversion"}

#custom logs
logfeast = { group = "dude.logFeast", name = "logger", version.ref = "libLogfeast" }

#firebase
google-firebase = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}

#material
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

#compose navigation
androidx-navigation-compose = { group  = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation"}
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltversion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }


